### ISSUE TITLE
keys with periods in them

### ISSUE THREAD

**Issue by JalfResi** [ajg/form#4]
A particular third-party API I wish to contact used periods in the key names. I have the keys in my structs labelled as such:

type whatever struct {
CleanupReturnCleaned bool   `form:"cleanup.returnCleaned"`
}

but when I run form.EncodeToString() I get:
cleanup%5C.returnCleaned=true

I've read the documentation in the Readme and have tried escaping the period with a back slash but that doesnt seem to have the desired effect. Am I misreading the readme, or is this not possible using ajg/form?

Cheers!

**Comment by ajg** [comment]
Let me investigate.

**Comment by ajg** [comment]
Hey @JalfResi,

Is what you want to have the period encoded without escaping—i.e. for the output to be `cleanup.returnCleaned=true`? That's currently not possible, because it would make decoding ambiguous in the general case. Still, you could use the following as a simple workaround:

```go

type whatever struct {
	Cleanup struct {
		ReturnCleaned bool `form:"returnCleaned"`
	} `form:"cleanup"`
}
```

Would that work for you?

**Comment by JalfResi** [comment]
Ok thanks!

**Comment by ajg** [comment]
FYI @JalfResi, with PR #10 there is now support for literal unescaped periods in key names. (See https://github.com/ajg/form#keys)
