### ISSUE TITLE
Proposal: Support for Reset

### ISSUE THREAD

**Issue by raphael** [ajg/form#8]
It would be useful for my use case if both the encoder and decoder structs exposed a `Reset` method which allowed changing the underlying `io.Writer` or `io.Reader` without having to create new instances. This makes it possible to use `sync.Pool` for example to manage a set of instances. The implementation would be trivial given that they don't have state other than the writer or reader. Would you consider a PR that added these? I'm thinking something like:

in `decode.go`:
```go
func (d *decoder) Reset(r io.Reader) {
	d.r = r
}
```

in `encode.go`
```go
func (e *encoder) Reset(w io.Writer) {
	e.w = w
}
```

**Comment by ajg** [comment]
@raphael, yeah, that seems reasonable to me; feel free to open a PR.

**Comment by ajg** [comment]
@raphael, I'm going to take a stab at adding this functionality and was hoping you could share your thoughts on these:

1. Does it matter for your purposes whether the setters are named `Reset` versus something like `SetReader` and `SetWriter`? (Possibly with matching getters named `Reader()` and `Writer()`.)
2. What about having the setters return something useful? (Either the prior `io.Reader`/`io.Writer` value, or the `Decoder`/`Encoder` itself to allow chaining.)
3. Instead of adding getters & setters at all how about just exporting (or embedding) the reader/writer fields in the decoder/encoder structs, respectively?

Thanks
